### PR TITLE
Added AkeylessBackend

### PR DESCRIPTION
**Pull request by renanaAkeyless**
Added support to get secret form Akeyless secret management 
https://www.akeyless.io/

### CODE REVIEW

**Comment by OriMankali** [comment]
Hey @jayway  @silasbw or anyone from the maintainers please review this pr? We'd really like to get this approved and merged as part of this project. Thanks!

**Review by OriMankali — APPROVED** [review]

**Review by Flydiverny — COMMENTED** [review]
Yes, I'm aware of this PR. While I understand your want to get attention or at least some kind of acknowledgement of existance 😄 
I recommend reaching out on the community Slack instead of emails and random pings, no one at Jayway is working with KES, well except for me currently being employed there. Silas and GoDaddy is not actively taking part in maintaining KES either!

There is, sadly, not much active time put into KES maintenance, mainly it is me!
With this being a new backend implementation of a new service which I haven't really heard about before!
I haven't seen any user demand yet, so it hasn't been on the top of things on my limited contribution time! 🙂 

That said I do appreciate the contribution and sorry for the delay/lack of response! 😄 

To focus on the contribution;
It was blocked a bit by wanting to get the 8.0.0 change out the door first which has now been resolved.

The changes look sane tho I don't really have any knowledge of neither your library or service.

`package-lock.json` needs to be fixed it looks like it has been entirely nuked diff wise.

For future endeavors I recommend you make a contribution to the Go rewrite ESO https://github.com/external-secrets/external-secrets.

We can land the backend here in KES first as well, but preferably you commit to contributing to ESO as well and preferably keeping it up to date with future changes!

**Comment by davidmortiz** [comment]
@Flydiverny I'm actually interested in this change.  My company is a user of KES and AKeyless and having KES support it would be wonderful

**Comment by Flydiverny** [comment]
#767 was merged and released in 8.1.0

**Pull request closed without merging**
