### PR TITLE
feat(poller): lodash template preprocess for template field

### PR DESCRIPTION
**Pull request by intpp**
Details: https://github.com/external-secrets/kubernetes-external-secrets/issues/625

### CODE REVIEW

**Comment by moolen** [comment]
Leeets go! Thanks @intpp  and @eshepelyuk for your contribution!
I didn't get to play with it yet, but from a first glance it looks good!

Could you please add e2e tests ([take a look here for reference](https://github.com/external-secrets/kubernetes-external-secrets/blob/master/e2e/tests/secrets-manager.test.js#L23-L78))? That would be really valuable.

For now only `template.stringData` is supported. Do you think it makes sense to also support `template.data` in scope of this PR?

**Comment by eshepelyuk** [comment]
@moolen please review examples in #625, they should explain everything by example.

Entire `ExtSec.template` is suported, i.e. `stringData`, `data`, `labels`, `annotations` etc 
I.e. resulting K8S `Secret` is completely customizable with `lodash` templating.

**Comment by eshepelyuk** [comment]
@intpp is it OK to add e2e tests and taking the input data from #625 ?

**Comment by moolen** [comment]
I see now. looks good!
What about `package-lock.json`, why was it removed?

**Comment by eshepelyuk** [comment]
Not sure, let's wait for @intpp :)

**Comment by intpp** [comment]
@moolen i'll revert package-lock.json (it's maybe my settings removed it)

i'll try to add e2e

**Comment by eshepelyuk** [comment]
@moolen README is updated.

**Comment by eshepelyuk** [comment]
@moolen could you plz help to debug e2e test ?

I've added a very sample case and Secret is not created, i.e. test return `undefined`

You could check this PR
https://github.com/intpp/kubernetes-external-secrets/pull/1

How to understand what is the error ?

**Comment by moolen** [comment]
I took a quick look. It basicially boils down to this line: https://github.com/external-secrets/kubernetes-external-secrets/pull/626/files#diff-17502f4c1fbf75e34c5969bc001d3f582249700e55e4902264c3ba55a8e15d3fR98

if `template.stringData` would be defined then it would work as expected in the test scenario.
RN it copies over the `<%= "Hello" %>` to the actual secret. This value is not a valid label value (must be `alphanumeric` + `_-.`) - because of that the secret won't be created.

By the way You can run the tests locally with `./run-e2e-test.sh` from the `e2e` dir.

**Comment by eshepelyuk** [comment]
> I took a quick look. It basicially boils down to this line: https://github.com/external-secrets/kubernetes-external-secrets/pull/626/files#diff-17502f4c1fbf75e34c5969bc001d3f582249700e55e4902264c3ba55a8e15d3fR98
> 
> if `template.stringData` would be defined then it would work as expected in the test scenario.
> RN it copies over the `<%= "Hello" %>` to the actual secret. This value is not a valid label value (must be `alphanumeric` + `_-.`) - because of that the secret won't be created.
> 

Thnx a lot for the clarification. !

> By the way You can run the tests locally with `./run-e2e-test.sh` from the `e2e` dir.

Unfortunately I cant because 
> had no luck installing kind on windows, so only able to test PR via GitHub actions.

**Comment by eshepelyuk** [comment]
@moolen @intpp e2e test is added.

**Review by moolen — APPROVED** [review]
LGTM! Thanks for adding the e2e tests!

**Comment by eshepelyuk** [comment]
Hi @moolen 

Thnx for accepting our contribution !
Obvious question, any plan to release a new version soon ?

**Comment by moolen** [comment]
@eshepelyuk I think it makes sense to create one. I'll try to find some time to figure it out or maybe @Flydiverny can you help us?

**Comment by eshepelyuk** [comment]
Thnx for the explanation.

**Comment by Flydiverny** [comment]
A 6.4.0 release has been made :) thanks for the contribution!

**Comment by eshepelyuk** [comment]
Great 🚀 👍 ❕ ❕ ❕

**Comment by eshepelyuk** [comment]
@moolen @Flydiverny could I request to post an release announcement to Slack channel ?

**Pull request merged**
