### PR TITLE
feat: restart watcher if no events seen for specified period

### PR DESCRIPTION
**Pull request by Flydiverny**
alternative to #531 
To see if that can solve #362 

A build of this PR is available on docker hub:

[`flydiverny/kubernetes-external-secrets:6.0.0-with.pr532.27286e0`](https://hub.docker.com/layers/flydiverny/kubernetes-external-secrets/)

```yaml
image:
  repository: flydiverny/kubernetes-external-secrets
  tag: 6.0.0-with.pr532.27286e0
```

Todo
- [x] Configurable restart timeout

### CODE REVIEW

**Comment by 2mf** [comment]
This would PR would help me a lot

**Comment by sparky005** [comment]
Does this resolve https://github.com/external-secrets/kubernetes-external-secrets/issues/399 as well?

**Comment by Flydiverny** [comment]
@sparky005 I dont think so

**Comment by Darius-Ndubi** [comment]
Hi @Flydiverny, I am having this [issue](https://github.com/external-secrets/kubernetes-external-secrets/issues/362) . POLLER_INTERVAL_MILLISECONDS:  30000 and WATCH_TIMEOUT:                 60000 on KES version: 8.3.2. Polling fails with error ```ERROR, Error: connect ETIMEDOUT```. Is there another way to force the watcher to restart?

**Pull request merged**
