### PR TITLE
Log base w/ configurable pid and hostname keys

### PR DESCRIPTION
**Pull request by SocalNick**
`hostname` isn't always desireable and is somewhat inaccurate given
os.hostname is the pod name in kubernetes

### CODE REVIEW

**Comment by SocalNick** [comment]
👋 folks! My company is using k8s-external-secrets...thanks so much for developing / maintaining it!

The [pino default log base](https://getpino.io/#/docs/api?id=base-object) uses hostname as the key for `os.hostname()`. In a kubernetes context, this evaluates to the pod name. When our log aggregation platform processes these logs w/ hostname set to the pod name, it can't decorate the logs w/ additional tags for the actual underlying host. This change maintains the default behavior but allows an operator to choose alternate keys for the pid and hostname of the pino log base.

I didn't see any tests around configuration, but if this feels like it requires a test, happy to add one if you can point me in the right direction.

Also, this likely needs to be documented. Can you point me towards the docs that I should update?


Thanks!

Nick

**Comment by SocalNick** [comment]
@Flydiverny @riccardomc any chance you could take a look at this PR? Thanks!

**Review by Flydiverny — APPROVED** [review]
Also see #864

**Comment by Flydiverny** [comment]
Regarding docs it would be here:
https://github.com/external-secrets/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/README.md#configuration

**Comment by SocalNick** [comment]
Added documentation, thanks again for your consideration!

**Comment by Flydiverny** [comment]
Released as [8.4.0](https://github.com/external-secrets/kubernetes-external-secrets/releases/tag/8.4.0)

**Pull request merged**
